import csv

f = open("gallery.html", "w")
f.write('<!doctype html>' + '\n')
f.write('<html lang="en">' + '\n')
f.write('  <head>' + '\n')
f.write('    <meta charset="utf-8">' + '\n')
f.write('    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">' + '\n')
f.write('    <meta name="description" content="">' + '\n')
f.write('    <meta name="author" content="">' + '\n')
f.write('    <link rel="icon" href="img/favicon.jpg">' + '\n')
f.write('\n')
f.write('    <title>Jean Cooper</title>' + '\n')
f.write('\n')
f.write('    <!-- Bootstrap core CSS -->' + '\n')
f.write('    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">' + '\n')
f.write('\n')
f.write('    <!-- Custom styles for this template -->' + '\n')
f.write('    <link href="css/cover.css" rel="stylesheet">' + '\n')
f.write('    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">' + '\n')
f.write('    <link rel="stylesheet" href="css/gallery-grid.css">' + '\n')
f.write('  </head>' + '\n')
f.write('\n')
f.write('  <body class="text-center">' + '\n')
f.write('\n')
f.write('    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">' + '\n')
f.write('      <header class="masthead mb-auto">' + '\n')
f.write('        <div class="inner">' + '\n')
f.write('          <nav class="nav nav-masthead justify-content-center">' + '\n')
f.write('            <a class="nav-link" href="index.html">Home</a>' + '\n')
f.write('            <a class="nav-link" href="her_story.html">Her Story</a>' + '\n')
f.write('            <a class="nav-link active" href="gallery.html">Gallery</a>' + '\n')
f.write('            <a class="nav-link" href="contact.html">Contact</a>' + '\n')
f.write('          </nav>' + '\n')
f.write('        </div>' + '\n')
f.write('      </header>' + '\n')
f.write('\n')
f.write('      <main role="main" class="inner cover">' + '\n')
f.write('        <div class="container gallery-container">' + '\n')
f.write('\n')
f.write('          <div class="tz-gallery">' + '\n')
f.write('\n')
f.write('            <div class="row">' + '\n')
f.write('\n')

with open('gallery.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        f.write('              <div class="col-sm-1 col-md-2">' + '\n')
        f.write(f'                <a class="lightbox" href="images/{row["Name"]}.jpg">' + '\n')
        f.write(f'                  <img src="images/{row["Name"]}.jpg" alt="{row["Alt"]}">' + '\n')
        f.write('                </a>' + '\n')
        f.write('              </div>' + '\n')
        print(f'\t{row["Name"]} has caption = {row["Caption"]} and alt = {row["Alt"]}.')
        line_count += 1
    print(f'Processed {line_count} lines.')

f.write('\n')
f.write('            </div>' + '\n')
f.write('\n')
f.write('          </div>' + '\n')
f.write('\n')
f.write('          <footer class="mastfoot mt-auto">' + '\n')
f.write('            <div class="inner">' + '\n')
f.write('              <p><br></p>' + '\n')
f.write('            </div>' + '\n')
f.write('          </footer>' + '\n')
f.write('\n')
f.write('        </div>' + '\n')
f.write('      </main>' + '\n')
f.write('    </div>' + '\n')
f.write('\n')
f.write('    <!-- Bootstrap core JavaScript================================================== -->' + '\n')
f.write('    <!-- Placed at the end of the document so the pages load faster -->' + '\n')
f.write('    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>' + '\n')
f.write("    <script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery-slim.min.js\"><\/script>')</script>" + '\n')
f.write('    <script src="../../assets/js/vendor/popper.min.js"></script>' + '\n')
f.write('    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>' + '\n')
f.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>' + '\n')
f.write('    <script>' + '\n')
f.write("      baguetteBox.run('.tz-gallery');" + '\n')
f.write('    </script>' + '\n')
f.write('  </body>' + '\n')
f.write('</html>' + '\n')